root = Tk()
Label(root, text="Write your name:", font=("", 15)).place(x=15, y=50)
name = Entry(root, width=50)
name.place(x=80, y=85)
def questions(): 
    root.destroy()
    questions = Tk()
    Label(questions, text="What's your favorite sport?").place(x=15, y=15)
    Entry(questions, width=50).place(x=25, y=35)
    Label(questions, text="What's your favorite TV show?").place(x=15, y=55)
    Entry(questions, width=50).place(x=25, y=75)
    Label(questions, text="What's your favorite food?").place(x=15, y=95)
    Entry(questions, width=50).place(x=25, y=115)
    questions.title("questions")
    questions.resizable(False, False)
    questions.geometry("500x250")
    questions.mainloop()
Button(root, text="Submit and start!", command=questions).place(x=35, y=150)
root.title("Survey")
root.geometry("500x200")
root.resizable(False, False)
root.mainloop()
